### ISSUE TITLE
Import error in 0.86.0

### ISSUE THREAD

**Issue by bramburn** [bramburn/pi#957]
> Synced from upstream **earendil-works/pi#9794** (closed, not implemented there).

- **Source:** https://github.com/earendil-works/pi/issues/9794
- **Upstream author:** @yonikremer
- **Upstream opened:** 2026-09-20T06:41:03Z
- **Upstream closed:** 2026-09-20T06:41:12Z
- **Upstream labels:** bug, untriaged

---

### What happened?

When updating to 0.86.0 and updating all pi packages and reloading, got this error:
```
Error: Cannot find module
 'C:\Users\yonik\AppData\Roaming\npm\node_modules\@earendil-works\pi-coding-agent\dist\bundle\chunks\openai-responses-TFDINO6W.js' imported from
 C:\Users\yonik\AppData\Roaming\npm\node_modules\@earendil-works\pi-coding-agent\dist\bundle\chunks\chunk-JVUZSMYM.js
```

### Steps to reproduce

update to 0.86.0, install my user packages and update. I am using windows.
```
User packages:
  npm:@juicesharp/rpiv-ask-user-question
  npm:pi-background-tasks
  npm:@narumitw/pi-goal
  npm:@narumitw/pi-usage
  npm:pi-caveman
  npm:pi-smart-compact
  npm:pi-autoresearch
  npm:pi-extensible-workflows
  npm:@earendil-works/pi-server
  npm:@earendil-works/pi-tui
  npm:remote-pi
  npm:pi-worktrees
  npm:pi-queue-steer-factory
  npm:pi-fabric
  npm:pi-meta-oauth
  npm:@juicesharp/rpiv-todo
  npm:pi-lens
  npm:@dietrichgebert/ponytail
  npm:@injaneity/pi-computer-use
  npm:pi-btw
  npm:pi-web-search
```

### Version

0.86.0

---

## Fork notes

Upstream closed this without a fix (auto-close or no-action). The fork can implement it independently.

- [ ] Reproduce / confirm against fork `main`
- [ ] Decide on scope: minimal patch vs. broader refactor
- [ ] Implement
- [ ] Add regression test under `packages/coding-agent/test/suite/regressions/`
